services:
  redis:
    image: docker.io/library/redis
    container_name: redis
    hostname: redis
    networks:
      - redis
    ports:
      - 6379:6379
    restart: always
    logging:
      driver: "json-file"
      options:
          max-size: "5m"

networks:
  redis:
    name: redis
